GET http://localhost:3001/info

###
//gets them all
GET http://localhost:3001/api/persons

###
GET http://localhost:3001/api/persons/68208cfd10079ce9f655a3c1

###
//deletes one of them
DELETE http://localhost:3001/api/persons/68222c91222340349fb4cb4d

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Diana",
    "number":"55-555555"
}

###

GET https://phonebook-5khm.onrender.com/api/persons
